---
# tasks file for java
- name: install java package using yum module
  yum:
   name: java
   state: latest
  tags: java
# if already installed skip the installation use tags
- command: java -version
  tags: java version
- name: set the environment variables
  lineinfile:
   dest: /root/.bashrc
   line: "{{item}}"
  with_items:
   - 'export: JAVA_HOME="/usr/lib/jvm/jre-11-openjdk"'
   - 'export: PATH=$JAVA_HOME/bin:$PATH'
  tags: environments
